version: "3"

services:

  #==================================
  # Zookeeper
  #==================================
  zookeeper:
    build:
      context: zookeeper
      dockerfile: Dockerfile
    image: zookeeper
    networks:
    - bigdata-net
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    - 8080:8080
    environment:
      SERVER_HTTP_PORT: 9000
      API_HOST: localhost
      API_PORT: 9000

  #==================================
  # Postgres
  #==================================
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    image: postgres
    networks:
      - bigdata-net
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metastore

  #==================================
  # Hadoop
  #==================================
  hadoop:
    build:
      context: hadoop
      dockerfile: Dockerfile
    image: hadoop
    external_links:
      - zookeeper
    networks:
      - bigdata-net
    volumes:
      - hadoop_hdfs:/hdfs
    ports:
      - "50070:50070"
      - "50075:50075"
      - "8020:8020"
      - "8042:8042"
      - "8088:8088"
      - "8188:8188"
      - "19888:19888"

# Reset volumes
volumes:
  hadoop_hdfs: null

networks:
  default:
    external:
      name: bigdata-net
  bigdata-net:
    driver: bridge

