version: "3"

services:

  #==================================
  # Zookeeper
  #==================================
  zookeeper:
    build:
      context: zookeeper
      dockerfile: Dockerfile
    image: zookeeper
    networks:
    - bigdata-net
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    - 8080:8080
    environment:
      SERVER_HTTP_PORT: 9000
      API_HOST: localhost
      API_PORT: 9000

networks:
  default:
    external:
      name: bigdata-net
  bigdata-net:
    driver: bridge